### ISSUE TITLE
Hidden fields contained in FormField are not rendered by form.hidden_tag()

### ISSUE THREAD

**Issue by jpschaumloeffel** [lepture/flask-wtf#183]
When a nested form contains HiddenFields, the hidden_tag() method does not render them.

**Comment by lepture** [comment]
Could you describe it in this way:

1. what are you doing? (show me the code)
2. what do you expect?
3. what do you really get?

**Comment by jpschaumloeffel** [comment]
I put an example here:
https://gist.github.com/jpschaumloeffel/69269c2dbba6fbc36a39

form.hidden_tag() renders as:
```
<div style="display:none;"><input id="csrf_token" name="csrf_token" type="hidden" value="1432194888##708b97d2ace3555393ae1e81ff85b7e9d5b699e2"></div>
```

When you add `{{ subform.hidden_tag() }}` to the inner loop in the template, it does render the hidden fields of those forms, and that's what I do now, too.

I would have expected it to include all the hidden fields (innerforms-0-csrf_token, innerforms-1-csrf_token, innerforms-0-hidden, innerforms-1-hidden) within the output of form.hidden_tag().

**Comment by davidism** [comment]
Let's say you write some Jinja helper to render a form.  It knows to call `.hidden_tag()`, and also knows how to render `FormField`s.  So now you've just made automation harder, because each form will render all the hidden fields on it, so you get a bunch of redundant tags.

Explicit is better than implicit: render exactly what you mean to render, don't leave it up to magic recursive discovery.  With that said, it's also pretty trivial to write a subclass of `Form` that recurses down all nested forms to get all the hidden fields.
