### ISSUE TITLE
Add file validators

### ISSUE THREAD

**Issue by rduplain** [lepture/flask-wtf#2]
Add a set of file upload validators to use with a FileField. These might be added in a separate subpackage. Validators could include:
- is_file : check if field has a "file" attribute
- allow_types/deny_types : allow/deny certain content types, e.g. "image/jpeg", "text/html" etc.
- allow_filenames/deny_filenames : allow/deny certain filename patterns, e.g. ".jpg", ".txt" etc.
- is_image : checks that content type and filename match valid image (JPEG, GIF, TIFF, PNG).
- is_audio: checks that content type and filename match valid audio file (WAV, OGG etc)

---
- Bitbucket: https://bitbucket.org/danjac/flask-wtf/issue/2
- Originally Reported By: [Dan Jacob](http://bitbucket.org/danjac)
- Originally Created At: 2010-07-16 11:06:55

**Comment by davidism** [comment]
@dplepage @rduplain sorry to resurrect this old issue, but I'm trying to track down reproducible examples for [this line in `has_file`](https://github.com/lepture/flask-wtf/blob/23e29b70d1bf9f1500d0fc0ee25f57151f7eb9f5/flask_wtf/file.py#L21):

~~~python
# filename == None => the field was present but no file was entered
# filename == '<fdopen>' is for a werkzeug hack:
#   large file uploads will get stored in a temporary file on disk and
#   show up as an extra FileStorage with name '<fdopen>'
return self.data.filename not in [None, '', '<fdopen>']
~~~

As far as I can tell, even multi-gigabyte files don't produce `<fdopen>` filenames or extra entries, despite what the comment indicates. Nor can I figure out how to make a request that both populates `request.files` and doesn't provide a filename.  Even if it didn't have a filename, it would still be a valid file.

I noticed this while doing some cleanup, and would like to either create tests for it or remove it.  I know it's been a while, but any insight is appreciated.

**Comment by rduplain** [comment]
@davidism Perhaps Werkzeug versions changed how this behaves? I haven't used this in a long time, but I do recall that when this issue was posted, I could get `<fdopen>` from Werkzeug.

Also, just in case it's not clear, my comments in this thread are from migrating from the previous bitbucket repo (and are not authored by me).

**Comment by dplepage** [comment]
@davidism Short answer: I think you can remove it.

Long answer:

When parsing files, werkzeug uses a `tempfile.TemporaryFile` if the `content_length` exceeds 500*1024 ([source](https://github.com/pallets/werkzeug/blob/master/werkzeug/formparser.py#L41)).

In python 2, this results in a file named `'<fdopen>'`:
```python
>>> import tempfile
>>> tempfile.TemporaryFile().name
'<fdopen>'
```

However, I'm pretty sure that the fact that a `FileStorage` would actually GET this name was a bug in `werkzeug.formparser` - there was some way to post a file without a filename, in which case it would default to pulling the name off the stream. Looking at the code now, I don't think that's possible anymore.

It's worth noting that if it IS still possible, it'd actually be a much more serious bug now because werkzeug [clearly assumes that the stream will have a string name](https://github.com/pallets/werkzeug/blob/master/werkzeug/datastructures.py#L2629) and in python 3 `TemporaryFile().name` will be an integer instead of `'<fdopen>'`.

So I think the check is useless - if the bug's been fixed then the check isn't needed, and if it hasn't been fixed then werkzeug itself will crash before ever getting here 😄 .

**Comment by davidism** [comment]
That's also what I got out of reading the Werkzeug source, so I'll remove it.  Thanks.
