### ISSUE TITLE
csrf_token should store in the cookie not in the session

### ISSUE THREAD

**Issue by wingyiu** [lepture/flask-wtf#219]
csrf_token should store in the cookie not in the session. 
to validate a post/put request, should compare the submit token value in form or header with the cookie value.

user may use the memcached to implement the session.

**Comment by wingyiu** [comment]
no way to get the csrf_token value in pure ajax app.

**Comment by davidism** [comment]
If you have different requirements, it's trivial to add an `after_request` callback to add a cookie, header, etc. with this information, in the specific layout you need.

**Comment by siegerts** [comment]
Agreed.  Just spent hours troubleshooting why the csrf_token verification was returning False on POST requests.

**Comment by davidism** [comment]
Use the `CsrfProtect` extension and set the `X-CSRFToken` header for the request. This has been documented for some time: http://flask-wtf.readthedocs.io/en/v0.13.1/csrf.html#ajax. If you're not rendering templates and still need CSRF tokens, make an endpoint that responds with the result of `generate_csrf` then fetch it periodically, although you should probably be using OAuth tokens instead.

**Comment by davidism** [comment]
You can add the CSRF token as a response header. Your app would extract this header from responses it gets and add it to requests it makes.

~~~python
from flask_wtf.csrf import generate_csrf

@app.after_request
def add_csrf_token(response)
    response.headers.set('X-CSRFToken', generate_csrf())
    return response
~~~

Cookies, session or otherwise, become tricky when CORS and the browser's third-party cookie policy comes into play.  In that case, a server side session accessed through a session id token in the headers is most likely what you want.  I'm not clear why storing the token in the session wouldn't be acceptable in that case.

If you are still having issues, I'm going to need a much more detailed post about how to reproduce the issue you're having before I can offer a solution or fix.

**Comment by davidism** [comment]
I can successfully use the session cookie in a cross domain setup as shown here: https://gist.github.com/davidism/f84b0ee5ddd88b747192d792086eda74.  I still strongly suggest using a token and server side session and avoiding cookies when writing JavaScript frontends.  I am not sure what the security implications of disabling the browser's default behavior of blocking cross domain cookies is.
