### ISSUE TITLE
pkg_resources.get_distribution won't work on App Engine

### ISSUE THREAD

**Issue by lipis** [lepture/flask-wtf#261]
This [particular line](https://github.com/lepture/flask-wtf/blob/master/flask_wtf/__init__.py#L21) won't work on App Engine and I'm sure that there are quite a lot of people using Flask-WTF on App Engine..

One work around that can be done just to avoid this is demonstrated in this [pull request](https://github.com/gae-init/gae-init/pull/572) which is quite ugly and not really necessary I would say.

Can we just change it to simply writing the version in the file?

```python
__version__ = '0.13'
```

In understand that is quite cool to get the version number from the distribution, but is also not that hard to maintain it to avoid all this monkey patches on Google App Engine..

**Comment by lepture** [comment]
@davvid Let's remove `pkg_resources.get_distribution`. We can use bumpversion to manage versions.

**Comment by davvid** [comment]
I think you meant @davidism but fwiw I agree too ;-)

**Comment by davidism** [comment]
Sure, I'll revert it for now.

This appears to have been [addressed in setuptools back in 2009](https://github.com/pypa/setuptools/commit/33e3ec5eadb59ece949d4cad1231ff23780e4c02), so not sure why it's still happening.    Perhaps GAE has an outdated default version and setuptools can be updated?  If not, please consider reporting this as a bug in setuptools, since this probably shouldn't fail.

**Comment by lipis** [comment]
The `pkg_resources` can be imported but this particular function won't, because the way they are handling the 3rd party libraries.. Maybe in the future, but I doubt that..

**Comment by lipis** [comment]
Thank you guys for reverting it :D
