### ISSUE TITLE
Any plan to support reCAPTCHA v3? 

### ISSUE THREAD

**Issue by junwei-wang** [lepture/flask-wtf#363]

**Comment by Lucid-Network** [comment]
This just came to my mind when I just read the docs. Hidden recaptcha 3 is the king. An example would be awesome!.

**Comment by get-data-** [comment]
> This just came to my mind as well, when I read the docs. Hidden recaptcha 3 is the king. An example would be awesome!.

This is an example of a reCAPTCHA v3 form field. I tried it recently and it works just fine

**Comment by jonathanstegall** [comment]
Have any of you used the above example and accounted for what happens when a user fails the recaptcha? I thought it would maybe show them a manual recaptcha, but it doesn't seem to do anything. The JavaScript does return the message that it failed, but that appears to be the extent of it. What is supposed to happen in this case?

**Comment by get-data-** [comment]
> Have any of you used the above example and accounted for what happens when a user fails the recaptcha? I thought it would maybe show them a manual recaptcha, but it doesn't seem to do anything. The JavaScript does return the message that it failed, but that appears to be the extent of it. What is supposed to happen in this case?

In the event that the user gets a false positive response, (user is human but was scored below the cutoff threshold) you can handle it by returning a response with a form which utilizes reCaptcha v2 or some alternative authentication process.

**Comment by rmControls** [comment]
any progress on reCAPTCHA v3 implementation in Flask-wtf
